### GET products
GET http://localhost:8383/products

### product
GET http://localhost:8383/products/james

### POST - ADD A PRODUCT
POST http://localhost:8383/addproduct
Content-Type: application/json

{"name": "this_product_is_added_with_post",
"status": "sneakers"
}

### UPDATE STATUS OF A PRODUCT
PATCH http://localhost:8383/changestatus
Content-Type: application/json

{"name": "this_product_is_added_with_post",
"newStatus": "_updated_sneakers"
}


###DELETE A PRODUCT
DELETE http://localhost:8383/products
Content-Type: application/json

{
    "name": "this_product_to_delete__with_post"
}


